### ISSUE TITLE
Decoder error on Windows 10

### ISSUE THREAD

**Issue by wywhynot** [upscayl/upscayl#110]
Just tried using this for the first time and I chose to sharpen the image. I immediately got the Decoding error other people have mentioned

**Comment by aaronliu0130** [comment]
Please refrain from opening duplicate issues.

**Comment by wywhynot** [comment]
Sorry, I didn't see one for Windows 10, just Mac

**Comment by aaronliu0130** [comment]
ah wait for windows? That's a different problem. Did you use batch upscayl?

**Comment by wywhynot** [comment]
> ah wait for windows? That's a different problem. Did you use batch upscayl?

no

**Comment by aaronliu0130** [comment]
Do you have the logs?

**Comment by wywhynot** [comment]
> Do you have the logs?

I don't see log files in the folder. What would the file name be?

**Comment by aaronliu0130** [comment]
Ok, it appears the windows release doesn't have crash logs, so lets do a dev run:

0. Download this repo's code and unzip it into a folder. In a terminal, `cd` into that folder. Make sure `npm` is installed.
1. Install dependencies through `npm install`.
2. Start the dev run through `npm run`.

You should see logs appearing on the terminal if nothing goes wrong. Repeat the steps you used to trigger the error and reply with the logs.

**Comment by wywhynot** [comment]
I've never used npm or even know what it is. Can you send the Windows download link?

**Comment by aaronliu0130** [comment]
https://letmegooglethat.com/?q=npm

Altérnate answer: https://nodejs.org/dist/v18.10.0/node-v18.10.0-x64.msi

**Comment by NayamAmarshe** [comment]
> Just tried using this for the first time and I chose to sharpen the image. I immediately got the Decoding error other people have mentioned

I made a mistake in the code and the full decode error doesn't appear. Will fix it in the next release.

**Comment by CGMikeG** [comment]
I was having the same issue, I am not sure what else would trigger the DECODER ERROR but it looks like if the image is big or in a jpg format. It can trigger the error. I tried converting the image to PNG it was okay for small images and general image settings.

I got below error message when I tried to use Sharpening setting

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 25.00%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() vkWaitForFences failed -4

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() vkQueueSubmit failed -4
95.83%
vkQueueSubmit failed -4

Small jpeg files gave me below error.

E:\GITHUB\upscayl-main
info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
event - compiled client and server successfully in 391 ms (152 modules)
≡ƒÜÇ Icon Path:  E:\GITHUB\upscayl-main\main\build\icon.png
≡ƒÜÇ Development Mode? : true
≡ƒÜÇ RS Executable Path:  E:\GITHUB\upscayl-main\resources\win\bin\upscayl-
≡ƒÜÇ Models:  E:\GITHUB\upscayl-main\resources\models
wait  - compiling / (client and server)...
event - compiled client and server successfully in 234 ms (263 modules)
E:\Library\Photos\FBVeniceFlowerFieldPNG.png
E:\Library\Photos\FBVeniceFlowerField-.jpg
E:\Library\Photos\Output
FBVeniceFlowerField-.jpg
[9044:1021/062653.428:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by NayamAmarshe** [comment]
GPU compatibility issue. Seems like Vulkan isn't properly working with your hardware configuration.
