### ISSUE TITLE
Processed Images Take Up To Much Space On Your Hard Drive.  

### ISSUE THREAD

**Issue by DJboutit** [upscayl/upscayl#116]
I have tested Upscayl vs Qualityscaler each use different AI models the processed images look just about the same.  The difference is Upscayl image is 51mb and Qualityscaler 15.5mb one more same image Upscayl 40mb Qualityscaler 17mb.  Please take a look into this no processed should be 35mb+  like 85% should be like 17mb max.

**Comment by oelna** [comment]
Maybe as a feature request you could add output image format and quality fields to the UI. Could be some work, but would help, too.

**Comment by DJboutit** [comment]
> Maybe as a feature request you could add output image format and quality fields to the UI. Could be some work, but would help, too.

Maybe output quality of like 85% to 100% would me nice.  Set out put quality to 95% would keep images under 25mb they still look fine.

**Comment by aaronliu0130** [comment]
Adding on: The default should also be lowered.

**Comment by DJboutit** [comment]
I been processing image from a image set after they have been processed they are 550mb they should be 22mb to 25mb max 33mb.  JPGs are really compressed they are not PNG or Bitmap JPG files are 1/4 to 1/6 of the others.

**Comment by NayamAmarshe** [comment]
> I been processing images from a image set after they have been batch processed they are 550mb they should be 35 to 45mb. Batch images should be process to JPG PNGs are just a waste of space really.

JPGs are lossy, they compress images and have artifacts. I think it's better to have lossless PNGs with no artifacts that you can later convert to any other format that you like.

**Comment by DJboutit** [comment]
300mb+ images no thank you.  I have like 2.5TB of images if they were all PNG that would be 15TB to 25TB.  Another things is PNG take 5x to 10x longer to do any like load or change brightness.

**Comment by oelna** [comment]
> > I been processing images from a image set after they have been batch processed they are 550mb they should be 35 to 45mb. Batch images should be process to JPG PNGs are just a waste of space really.
> 
> JPGs are lossy, they compress images and have artifacts. I think it's better to have lossless PNGs with no artifacts that you can later convert to any other format that you like.

It is certainly correct to have lossless output as a possible format. All I'm saying is, in many cases I have to convert the output in a second step, and in another app, anyway, so I'd find it helpful, if there were a preference I could set (or even a toggle in the UI) in order to have a different output file format, eg. JPG or HEIC.

Choosing the quality on a case by case basis would be *chef's kiss*, but if it's easier to build I'd also settle for a set of predefined values, eg

- PNG (lossless)
- JPG (low, 40%)
- JPG (medium, 65%)
- JPG (high, 85%)

I think personally I'd pick `JPG (high)` about 90% of the time. 🤷🏻‍♂️

**Comment by DJboutit** [comment]
JPG we should be able to section the output quality from 80% to 100% with default should be like 95%.
