### ISSUE TITLE
Feature Request: Alternative file types?

### ISSUE THREAD

**Issue by rylehfhtagn** [upscayl/upscayl#120]
Would love to be able to save images as .bmp. The reason being that Windows caps .png wallpapers at an arbitrary file size, but that cap doesn't exist for .bmp

**Comment by NayamAmarshe** [comment]
I'll think about an output format option, maybe can add it when we add an image manipulation library but till then, adding the option just because of Windows doesn't seem enticing. Our project mostly focuses on cross platform utility, so it either has to make sense for Linux or make sense for all 3 platforms that we support.

**Comment by daNutzzzzz** [comment]
I would fully support more output formats (BMP...), i wanted to batch upscale thousands of BMP files using this great tool but the limited output formats has made me look elsewhere 😞.
