### ISSUE TITLE
homebrew cask got rejected because "macOS on ARM requires applications to be signed"

### ISSUE THREAD

**Issue by GETandSELECT** [upscayl/upscayl#191]
Hi

See https://github.com/Homebrew/homebrew-cask/pull/138932
I added a cask for upscayl and it go rejected because of missing signature for binary.

> Thank you for your submission @GETandSELECT. We are unable to accept it at this time because it does not pass Homebrew's signature verification check:
> 
>     macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.

Is it possible to sign the app and I will re-submitt the PR?

Thanks

Happy New Year

**Comment by aaronliu0130** [comment]
See #34 , I've tried the exact same thing before.

**Comment by NayamAmarshe** [comment]
I'll be more than happy to accept PRs. As we follow Linux-first philosophy, our focus is on making sure Upscayl works perfectly fine on Linux. The rest of the package managers on other platforms are not a priority and probably won't be in the near future because I do not use other platforms and I'm the only guy currently working on Upscayl. TGS963 is busy with our other project.

**Comment by aaronliu0130** [comment]
@NayamAmarshe  this is essentially same as #34, the package manager’s failing because the macOS app isn’t signed

**Comment by NayamAmarshe** [comment]
> @NayamAmarshe  this is essentially same as #34, the package manager’s failing because the macOS app isn’t signed

Oh right. I said the same thing there I believe 😅
