### ISSUE TITLE
Decoding Error: this image is possibly corrupt

### ISSUE THREAD

**Issue by TexasGadget** [upscayl/upscayl#209]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Trying to upscale using JPG or PNG image, Upscayl starts the magic, but crashes after a few seconds, with error message saying "Decoding Error: this image is possibly corrupt..." even though I know the images are not corrupt loading them them in Photoshop and ACDSee fine. I've used Upscayl for at least a dozen photos the last few days with no problems. 
![Screenshot 2023-01-17 215226 error message](https://user-images.githubusercontent.com/122954772/213081870-34540dca-c6ac-4c5d-9a8d-fd5230448ec0.png)

### To Reproduce

start converting using "sharpen image"
![Bridge Over Village Creek (My Monet 2)](https://user-images.githubusercontent.com/122954772/213082225-9c59e3ce-c8d4-4e46-a627-3cc17c1de10a.jpg)

### Expected Behavior

complete the magic cycle.

### Version/Commit Hash

2.0.1

### OS Specifics

Gforce 1070ti, Win 10

### Screenshots

![Screenshot 2023-01-17 215226 error message](https://user-images.githubusercontent.com/122954772/213082427-c9150a84-8ef9-4630-ae5b-9b9663b41228.png)

**Comment by NayamAmarshe** [comment]
This is a common issue. I get this too. It's a vulkan bug: vkEnumeratePhysicalDevices Failed Error 5.

I have no idea why this happens. We need to investigate this.

**Comment by Gaz83** [comment]
Same issue, just to add I have to computers with it installed.

2 PC's and out of the 2, PC 2 works fine but PC 1 has the same error.

PC 1 - Windows 11 - AMD Ryzen 9 3900X 32gb Ram and a Nvidia GT 710
PC 2 - Windows 10 - Intel i5-4690 16gb Ram and a Nvidia Quadro P1000

**Comment by dimitri-vs** [comment]
Same issue. Installed Upscayl earlier - was working fine for processing individual and batch images. Closed and then opened it later today and its giving this error.

**Comment by NayamAmarshe** [comment]
I'll further investigate this. Will fix this once and for all.

**Comment by DJboutit** [comment]
I have found sometimes wait a min of like 8hrs before trying again most of the time or resetting your works most of the time.

**Comment by CryShana** [comment]
The latest NVIDIA Game Driver 528.24 fixed this issue for me.

**Comment by TexasGadget** [comment]
> 

That did the trick. Don't know why, but it worked after updating driver.

**Comment by jujpenabe** [comment]
For me it just works with individual images, tested with a batch of just 2 images and this error came out.

**Comment by dragbeadle** [comment]
For what it's worth: I got the same problem on a Windows system with a 5000 series Ryzen and a GTX1000 series GPU. When I boot the exact same PC with the latest Pop!_OS Live and install Upscayl it works flawlessly.

**Comment by NayamAmarshe** [comment]
> For what it's worth: I got the same problem on a Windows system with a 5000 series Ryzen and a GTX1000 series GPU. When I boot the exact same PC with the latest Pop!_OS Live and install Upscayl it works flawlessly.
> 
> Updating to 528.24 drivers did however not fix the problem for me.

Yeah, it's an issue with Dual GPUs, especially with Nvidia. It's possible that node's child process spawn function launches the binaries in a weird way?

**Comment by dimitri-vs** [comment]
Wanted to update that updating to the latest NVIDIA Game Drive fixed the issue for me too.

**Comment by mrleemon** [comment]
I'm on Windows 10 and updating to the latest NVIDIA drivers doesn't fix the issue. I use an ASUS Geforce GT710 card. If I select "Digital Art" as the Upscaling Type, the error doesn't appear, but all the rest have this problem. I hope you find a fix.

**Comment by aaronliu0130** [comment]
@mrleemon Sounds like a different issue, would you kindly file another?

**Comment by moyisheep** [comment]
I solved this by https://substance3d.adobe.com/documentation/spdoc/gpu-drivers-crash-with-long-computations-128745489.html

problem solving original:https://github.com/xinntao/Real-ESRGAN/issues/106 @HolyWu

**Comment by moyisheep** [comment]
I use cmd to run upscayl , and then see error: vkQueueSubmit failed -4
I search this, then finally find the solution, maybe this will be a little method for you

**Comment by aaronliu0130** [comment]
@moyisheep Thanks for that! However, this issue is for ` vkEnumeratePhysicalDevices Failed Error 5.`, not vkQueueSubmit, and it was fixed after a driver update for most people. Thanks for your input!

**Comment by moyisheep** [comment]
@aaronliu0130 okay, Thanks for correcting me.

**Comment by fixups** [comment]
I'm getting the same problem now.

System: Ubuntu 20.04
Processor: AMD 5600G (yes, it has an integrated GPU)
GPU: RTX 3080 Ti

Upscayl was working perfectly (but slowly) on this system without the RTX 3080 Ti (using the 5600G iGPU). Then I purchased the NVIDIA card and installed it. Now the slowness is completely solved, as I cannot upscayl anymore.

Given the price of the 3080 Ti, this is... how can I put this without being mean... slightly irritating? :D

**Comment by yi** [comment]
> I'm getting the same problem now.
> 
> System: Ubuntu 20.04 Processor: AMD 5600G (yes, it has an integrated GPU) GPU: RTX 3080 Ti
> 
> Upscayl was working perfectly (but slowly) on this system without the RTX 3080 Ti (using the 5600G iGPU). Then I purchased the NVIDIA card and installed it. Now the slowness is completely solved, as I cannot upscayl anymore.
> 
> Given the price of the 3080 Ti, this is... how can I put this without being mean... slightly irritating? :D

I have a similar setup. A few suggestions:
1. install the server verison gpu driver `nvidia-driver-525-server`, This will avoid a lot of rendering selection problems
2. use `nvidia-smi -l 1` to monitor your nvidia gpu status 
3. upscayl model seems only use about 1-3G vram, and a low rang gpu card (4g varm) is good enough for it.

**Comment by fixups** [comment]
@yi: with your point number 3, are you suggesting that I dump the RTX 3080 Ti I just purchased and install a 1660 for example? :)

OK, so I have something new to add. Nobody has mentioned it, so maybe nobody has tried? I doubt it but here we go:

I managed to get Upscayl working on my system, and use the RTX 3080 Ti, by disabling the iGPU in the BIOS. Remember, I have an AMD 5600G in this PC, which has an integrated GPU.

I don't like disabling the iGPU (for various reasons), but I hope it's a temporary measure and that a real fix will be found.

Specifically, on my system, in the BIOS I have set:
```
Peripherals > Initial display output > PCIe 1 slot
Chipset > Integrated graphics > Disabled
```

It also works if I set:
```
Peripherals > Initial display output > PCIe 1 slot
Chipset > Integrated graphics > Auto
```
which I guess is also disabling the iGPU because the BIOS sees the GPU at boot, so it disables the iGPU. I guess that's what "Auto" does. Indeed, a utility like nvtop reports info about the RTX 3080 Ti only with these settings. When Upscayl was not working, nvtop could see both the iGPU and the GPU card, and reported the info for both.

The second set of settings (Auto) is the one I keep, because if I have to remove the RTX 3080 Ti for any reason, at least I don't have to worry about changing the BIOS settings before removing the card.

I have now rebooted at least 10 times with and without these settings, and Upscayl always works when the iGPU is disabled, and never works when the iGPU is enabled. Please note that Upscayl worked with the iGPU alone (which can only use 2GB of RAM BTW) before I installed the NVIDIA card. It's just that it was around 30 times slower on the iGPU than on the RTX 3080 Ti.

I may try to update the NVIDIA GPU driver at some point, but I'm a little bit reluctant to do it right now, because I'm pretty sure it will break things, and several people have already reported that for them it did not solve the problem anyway.

I confirm that when I had the problem, the error message was "vkEnumeratePhysicalDevices Failed Error 5".

Something I have tried and that did not work: I have tried changing the "GPU ID" in Upscayl's advanced options. I have tried ID 0 to 6 without any success.

**Comment by yi** [comment]
No I did not mean that. 
Read the source code, upscayl seems to rely on this model https://github.com/xinntao/Real-ESRGAN
and the problem you are having may have something to do with the cuda environment, like https://github.com/xinntao/Real-ESRGAN/issues/586

**Comment by fixups** [comment]
The post you are linking to is about "high CPU usage", which is not what happens with the issue we are discussing.

I guess Upscayl authors could try the proposed solution, which involves installing PyTorch manually with some different option which forces the use of CUDA, but I'm not even sure they can package Upscayl this way.

Anyway, what makes you think the proposed solution has anything to do with the issue we are discussing, which manifests itself with a
`vkEnumeratePhysicalDevices Failed Error 5`
and no high GPU usage?

Have you tried that yourself? Did it solve the above error?

Remember, Upscayl as it is works on GT 1030, GTX 1660 Super and RTX 3080 Ti, which all use CUDA. The issue seems to be triggered by the presence of more than one GPU in the PC. I don't understand your suggestions, so maybe you know something that we don't?

**Comment by aaronliu0130** [comment]
Closing this as the initial problem with drivers is fixed. For new issues please file new issues.

**Comment by aaronliu0130** [comment]
@DigitalMenace242 Not everybody has the same computer as you. For this person just updating the drivers work. For you, clearly not. File a new issue.

Also, Gigapixel is its own model and runner, while Upscayl is just a frontend. And drivers should always be updated.

**Comment by kadum0** [comment]
any update about this issue?

**Comment by aaronliu0130** [comment]
@kadum0 Please read my closing comment.
