### ISSUE TITLE
Discord or Matrix server for discussion on this project?

### ISSUE THREAD

**Issue by databoose** [upscayl/upscayl#212]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Hello, i really enjoy this project and i would like it if there is a chat service the community can go to talk about this project, preferably on matrix (element app) or discord. Thanks.

### Alternatives

Not applicable in this report, this is just a request.

**Comment by NayamAmarshe** [comment]
You can join these:

https://t.me/LinuxChats

https://t.me/iamnayam

**Comment by databoose** [comment]
I can't create an account on telegram as i don't have a phone number.

**Comment by NayamAmarshe** [comment]
> I can't create an account on telegram as i don't have a carrier phone number.

https://mezha.media/en/2022/12/07/telegram-has-added-the-option-to-register-without-a-sim-card/

I personally will not create a Discord account because of their privacy policy. Matrix would've been fine but I don't use it (and most people don't either). So I suppose GitHub and Telegram are the only 2 options I can really support, sorry :(
