### ISSUE TITLE
Upscayl does not upscale

### ISSUE THREAD

**Issue by cubyblue** [upscayl/upscayl#229]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

After launch an upscale : 
![image](https://user-images.githubusercontent.com/92122320/219095681-c97ba6fc-439c-4c47-9721-ac6628b9168c.png)
no error displayed, no picture in output folder

 

### To Reproduce

After completing step 1-2-3 and 4, and loading 

### Expected Behavior

has worked in the past, incompatibility with GPU driver version ?

### Version/Commit Hash

1.5 to 2. (latest) version 

### OS Specifics

Win10 - i5 12400f - RX 6700 (2.5.2 drivers)

### Screenshots

![image](https://user-images.githubusercontent.com/92122320/219096262-291bc193-2e73-4dac-a686-2452e5874580.png)

**Comment by aaronliu0130** [comment]
If you don’t have logs, you may follow these instructions: Download and install git from https://git-scm.com/download/win and node from https://nodejs.org/en/download/current/ (choose standalone installer 64 for both) then run these in your terminal:
```sh
git clone https://github.com/TGS963/upscayl
cd upscayl
npm install
npm run start
```
After the last command, upscayl should show up. Reproduce the error and send out the terminal output. `npm` will tell you about audit errors. These are due to #54 and currently expected.

**Comment by jess-2296** [comment]
> If you don’t have logs, you may follow these instructions: Download and install git from https://git-scm.com/download/win and node from https://nodejs.org/en/download/current/ (choose standalone installer 64 for both) then run these in your terminal:
> 
> ```shell
> git clone https://github.com/TGS963/upscayl
> cd upscayl
> npm install
> npm run start
> ```
> 
> After the last command, upscayl should show up. Reproduce the error and send out the terminal output. `npm` will tell you about audit errors. These are due to #54 and currently expected.

Hello, it's quite complicated to me as I don't understand the coding language. Do you perhaps have a video tutorial for this? :( I'm experiencing the same thing in using Upscayl. May I request for a recording?
Thank you so much.

**Comment by aaronliu0130** [comment]
You don't have to understand it, you only need to type it in your terminal (if you don't know what this is just search and open an app called "Command Prompt" or "cmd" for short)

**Comment by jess-2296** [comment]
> You don't have to understand it, you only need to type it in your terminal (if you don't know what this is just search and open an app called "Command Prompt" or "cmd" for short) I'm currently on mobile and if you still have problems I will get back to you later.

![image](https://user-images.githubusercontent.com/126000205/220405237-d278fc18-164d-4f41-bd05-b436d34aa2bf.png)

what should i do after this ?

**Comment by aaronliu0130** [comment]
wait until it finishes and `C:\Users\Jessa\upscayl>` shows up again

**Comment by jess-2296** [comment]
> wait until it finishes and `C:\Users\Jessa\upscayl>` shows up again

it stopped here .. or is it still running ? 
![image](https://user-images.githubusercontent.com/126000205/220407848-d76dc644-7fbb-4ed1-93a9-1b2e221db327.png)

**Comment by aaronliu0130** [comment]
I think so. If you can't type anything then it's still running.

**Comment by jess-2296** [comment]
> I think so. If you can't type anything then it's still running.

what is this ?  is it harmful ?
![image](https://user-images.githubusercontent.com/126000205/220409115-a318cb0d-ec82-4d0a-8f5b-c79f163c548b.png)

**Comment by aaronliu0130** [comment]
It isn't harmful, it's the library for this app

**Comment by jess-2296** [comment]
it's done  but upscayl is still not working :(
![image](https://user-images.githubusercontent.com/126000205/220409271-92d88c69-e136-4717-a8fe-15d204d2b31d.png)

**Comment by aaronliu0130** [comment]
Yeah copy that over

Also, what GPU do you use?

**Comment by jess-2296** [comment]
> Yeah copy that over
> 
> Also, what GPU do you use?

what do you mean copy that over ?

Nvidia

**Comment by aaronliu0130** [comment]
Copy the output of `npm run start` (`info - Disabled` ⇒ `Done upscaling`) and, if you can, enclose it in a details element or enclose it in ``` (triple backticks)

**Comment by jess-2296** [comment]
> Copy the output of `npm run start` (`info - Disabled` ⇒ `Done upscaling`) and, if you can, enclose it in a details element or enclose it in ``` (triple backticks)

where to paste it ?

**Comment by jess-2296** [comment]
> Here. Do something like this: <details>C:\Users\Jessa\upscayl>npm run start

> upscayl@2.0.1 start
> tsc && electron .


C:\Users\Jessa\upscayl
info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from C:\Users\Jessa\upscayl\renderer\babel.config.js

≡ƒî╝ daisyUI components 2.39.1  https://github.com/saadeghi/daisyui
  Γ£ö∩╕Ä Including:  base, components, themes[29], utilities

event - compiled client and server successfully in 17.8s (166 modules)
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

≡ƒÜÇ ICON PATH:  C:\Users\Jessa\upscayl\main\build\icon.png
≡ƒÜÇ UPSCAYL EXEC PATH:  C:\Users\Jessa\upscayl\resources\win\bin\upscayl-
≡ƒÜÇ MODELS PATH:  C:\Users\Jessa\upscayl\resources\models
≡ƒÜÇ FFMPEG PATH:  C:\Users\Jessa\upscayl\node_modules\upscayl-ffmpeg\bin\win\x64\ffmpeg.exe
wait  - compiling / (client and server)...
event - compiled client and server successfully in 4.5s (288 modules)
C:\Users\Jessa\Downloads\pexels-artem-podrez-6941448-removebg-preview.png
≡ƒÜÇ => fileName pexels-artem-podrez-6941448-removebg-preview
≡ƒÜÇ => fileExt .png
≡ƒåÖ COMMAND:  -i C:\Users\Jessa\Downloads/pexels-artem-podrez-6941448-removebg-preview.png -o C:\Users\Jessa\Downloads/pexels-artem-podrez-6941448-removebg-preview_upscayl_4x_realesrgan-x4plus.png -s 4 -m C:\Users\Jessa\upscayl\resources\models -n realesrgan-x4plus  -f png
Done upscaling
 </details>

**Comment by jess-2296** [comment]
> Here. Do something like this: 
<details> 
C:\Users\Jessa\upscayl>npm run start

> upscayl@2.0.1 start
> tsc && electron .


C:\Users\Jessa\upscayl
info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from C:\Users\Jessa\upscayl\renderer\babel.config.js

≡ƒî╝ daisyUI components 2.39.1  https://github.com/saadeghi/daisyui
  Γ£ö∩╕Ä Including:  base, components, themes[29], utilities

event - compiled client and server successfully in 17.8s (166 modules)
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

≡ƒÜÇ ICON PATH:  C:\Users\Jessa\upscayl\main\build\icon.png
≡ƒÜÇ UPSCAYL EXEC PATH:  C:\Users\Jessa\upscayl\resources\win\bin\upscayl-
≡ƒÜÇ MODELS PATH:  C:\Users\Jessa\upscayl\resources\models
≡ƒÜÇ FFMPEG PATH:  C:\Users\Jessa\upscayl\node_modules\upscayl-ffmpeg\bin\win\x64\ffmpeg.exe
wait  - compiling / (client and server)...
event - compiled client and server successfully in 4.5s (288 modules)
C:\Users\Jessa\Downloads\pexels-artem-podrez-6941448-removebg-preview.png
≡ƒÜÇ => fileName pexels-artem-podrez-6941448-removebg-preview
≡ƒÜÇ => fileExt .png
≡ƒåÖ COMMAND:  -i C:\Users\Jessa\Downloads/pexels-artem-podrez-6941448-removebg-preview.png -o C:\Users\Jessa\Downloads/pexels-artem-podrez-6941448-removebg-preview_upscayl_4x_realesrgan-x4plus.png -s 4 -m C:\Users\Jessa\upscayl\resources\models -n realesrgan-x4plus  -f png
Done upscaling
</details>

**Comment by aaronliu0130** [comment]
And your result is also blank image with no image at `C:\Users\Jessa\Downloads/pexels-artem-podrez-6941448-removebg-preview_upscayl_4x_realesrgan-x4plus.png`?

**Comment by jess-2296** [comment]
> And your result is also blank image with no image at `C:\Users\Jessa\Downloads\pexels-artem-podrez-6941448-removebg-preview_upscayl_4x_realesrgan-x4plus.png`?

yes :( here's the result 
![image](https://user-images.githubusercontent.com/126000205/220413543-6d1c0681-35ff-46f4-8f61-8b3f175f9041.png)

**Comment by aaronliu0130** [comment]
Are your following runtimes updated?
* Microsoft .NET Core 3 Runtime
* Microsoft Windows Desktop Runtime 7
* Microsoft Visual C++ Redistributable x64 and x86

**Comment by jess-2296** [comment]
> * Microsoft Visual C++ Redistributable x64 and x86

Sorry, I'm not familiar with that. where can I check it ?

**Comment by aaronliu0130** [comment]
Report their versions shown in Programs and Features.

**Comment by jess-2296** [comment]
> Report their versions shown in Programs and Features.

This is what I have 
![image](https://user-images.githubusercontent.com/126000205/220417119-1fb25772-b65b-4f8d-be10-c01fb531b85c.png)
![image](https://user-images.githubusercontent.com/126000205/220417291-d5cd06fa-0436-4912-baa6-156def0a46ae.png)

**Comment by aaronliu0130** [comment]
You should install the Visual C++ 2015-2022 Redistributable

**Comment by nuttapolllll** [comment]
i have same problem 

C:\Users\Acer\upscayl>npm install
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated @types/electron@1.6.10: This is a stub types definition for electron (https://github.com/electron/electron). electron provides its own type definitions, so you don't need @types/electron installed!

added 647 packages, and audited 648 packages in 26s

65 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 9.5.1 -> 9.6.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.2
npm notice Run npm install -g npm@9.6.2 to update!
npm notice

**Comment by aaronliu0130** [comment]
@nuttapolllll please post the run logs

**Comment by nuttapolllll** [comment]
> 

Microsoft Windows [Version 10.0.19044.2364]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Acer>git clone https://github.com/TGS963/upscayl
fatal: destination path 'upscayl' already exists and is not an empty directory.

C:\Users\Acer>cd upscayl

C:\Users\Acer\upscayl>npm install

up to date, audited 648 packages in 932ms

65 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\Acer\upscayl>npm run startgit clone https://github.com/TGS963/upscayl
npm ERR! Missing script: "startgit"
npm ERR!
npm ERR! Did you mean this?
npm ERR!     npm start # Start a package
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Acer\AppData\Local\npm-cache\_logs\2023-03-23T08_05_02_779Z-debug-0.log

C:\Users\Acer\upscayl>cd upscayl

C:\Users\Acer\upscayl\upscayl>npm install

up to date, audited 648 packages in 970ms

65 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\Acer\upscayl\upscayl>npm run start

> upscayl@2.0.1 start
> tsc && electron .


C:\Users\Acer\upscayl\upscayl
info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from C:\Users\Acer\upscayl\upscayl\renderer\babel.config.js

≡ƒî╝ daisyUI components 2.51.4  https://daisyui.com
  Γ£ö∩╕Ä Including:  base, components, 29 themes, utilities
  Γ¥ñ∩╕Ä Support daisyUI:  https://opencollective.com/daisyui

event - compiled client and server successfully in 3.4s (166 modules)
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

≡ƒÜÇ ICON PATH:  C:\Users\Acer\upscayl\upscayl\main\build\icon.png
≡ƒÜÇ UPSCAYL EXEC PATH:  C:\Users\Acer\upscayl\upscayl\resources\win\bin\upscayl-
≡ƒÜÇ MODELS PATH:  C:\Users\Acer\upscayl\upscayl\resources\models
≡ƒÜÇ FFMPEG PATH:  C:\Users\Acer\upscayl\upscayl\node_modules\upscayl-ffmpeg\bin\win\x64\ffmpeg.exe
wait  - compiling / (client and server)...
event - compiled client and server successfully in 1026 ms (269 modules)

**Comment by nuttapolllll** [comment]
and i have installed these program your recommend

Microsoft .NET Core 3 Runtime
Microsoft Windows Desktop Runtime 7
Microsoft Visual C++ Redistributable x64 and x86

**Comment by nuttapolllll** [comment]
![Untitled-1 copy](https://user-images.githubusercontent.com/128639236/227142075-bb82cff8-7c55-43cd-ae5d-73a000aa81bc.jpg)

**Comment by aaronliu0130** [comment]
@nuttapolllll Did you reproduce the bug while in `npm run start`?

**Comment by project-13** [comment]
Hello,
I think it's linked to the size of the image :
- 512 pixels upscale to 2024 => OK
- 2024 pixels upscale to 8192 pixels => OK
- 8192 pixels upscale to 32768 => KO

**Comment by bastegk2** [comment]
I have this bug too, Yesteday Upscaly works now it has stop, (said my GPU is not corret (vulkan), than i have use command at the Theard to repair a other problem and now i have this problem.

**Comment by bastegk2** [comment]
thanks for the fast answering ). I have install 2 Bum map generator with node.js (iam new in theses section) after Upscayl ( as possible reason?). 

Great thanks 👍

**Comment by Deal17291** [comment]
I've installed Upscayl and use a Mac mini (late 2012) with macOS 10.14.6 and get errors like the one at the screenshot:

![2023-04-10_16-02-16](https://user-images.githubusercontent.com/130373751/230916918-aed093bb-10d3-49ba-a749-0b503c565d34.jpg)

I converted from .jpg to .png - no results, only the error. The output path is correct and the write permissions are also.
I tried different pictures with no success.

Is there anybody who can help me please?

Thanks a lot ☺️

**Comment by aaronliu0130** [comment]
@Deal17291 Try #209 , update your drivers

**Comment by aaronliu0130** [comment]
@Deal17291 That might be #98 .

**Comment by Deal17291** [comment]
@aaronliu0130 I tested Upscayl 1.2.0 and got this JavaScript error (JDK 8u361),
![2023-04-10_19-35-58](https://user-images.githubusercontent.com/130373751/230958645-5cd80af4-3607-4813-9848-ac693d0e05a4.jpg)
whilst V. 1.5.0 until 2.0.1 gave me the decoding error.
I will try the next version 2.5.0 when released.

**Comment by aaronliu0130** [comment]
Is this fixed?

**Comment by Deal17291** [comment]
@aaronliu0130 It is not fixed in V. 2.5. First I saw the Screenshot left, after the second confirmation by “OK” the right one appears. The app didn’t close, it has to be quit manually.

 

Von: Aaron Liu ***@***.***>
Antworten an: upscayl/upscayl ***@***.***>
Datum: Sonntag, 14-Mai 2023 um 01:31
An: upscayl/upscayl ***@***.***>
Cc: Deal17291 ***@***.***>, Mention ***@***.***>
Betreff: Re: [upscayl/upscayl] Upscayl does not upscale (Issue #229)

 

Is this fixed?

**Comment by aaronliu0130** [comment]
@Deal17291 Yours is a different issue, #98.

**Comment by Deal17291** [comment]
@aaronliu0130 Sorry, I can’t work with that application.

 

Von: Aaron Liu ***@***.***>
Antworten an: upscayl/upscayl ***@***.***>
Datum: Sonntag, 14-Mai 2023 um 20:41
An: upscayl/upscayl ***@***.***>
Cc: Deal17291 ***@***.***>, Mention ***@***.***>
Betreff: Re: [upscayl/upscayl] Upscayl does not upscale (Issue #229)

 

@Deal17291 Yours is a different issue, #98.

**Comment by aaronliu0130** [comment]
What does that mean?

**Comment by Deal17291** [comment]
The app does not work correctly on my computer, I’ll give up.

 

Thank you for trying to help me.

 

 

Von: Aaron Liu ***@***.***>
Antworten an: upscayl/upscayl ***@***.***>
Datum: Dienstag, 16-Mai 2023 um 20:56
An: upscayl/upscayl ***@***.***>
Cc: Deal17291 ***@***.***>, Mention ***@***.***>
Betreff: Re: [upscayl/upscayl] Upscayl does not upscale (Issue #229)

 

What does that mean?

**Comment by aaronliu0130** [comment]
Which, as I said in my reply, is because GitHub has removed access to anything other than MacOS 11+., so we won't be supporting MacOS 10.x going forward.

**Comment by NayamAmarshe** [comment]
> @aaronliu0130 It is not fixed in V. 2.5. First I saw the Screenshot left, after the second confirmation by “OK” the right one appears. The app didn’t close, it has to be quit manually.
> 
> ![upscayl-2 5 1-mac](https://github.com/upscayl/upscayl/assets/130373751/ad295250-7120-4e17-914f-ef4a56e8d09d)

We are not supporting MacOS X anymore. That's why it won't work well on anything below MacOS 11.
