### ISSUE TITLE
Upscayl for tiling images

### ISSUE THREAD

**Issue by oemsysadm** [upscayl/upscayl#272]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

When upscaling an image that is designed to be tiled, the resulting image will have artifacts around the seams from the upscaling that were not present on the original image. In some cases these look severe, and in some cases they are subtle. For those working with repeating textures for things like 3D models or patterns designed to be printed on fabric or paper, this becomes an issue that is not easily fixed manually and in bulk.

### Description

Add an option or upscaling method that address this and which creates images where all the outer pixels line up with their counterparts on the opposite edge/corner.

### Alternatives

Other than attempting to manually fix the seam, I can't think of a way. This is unfeasible when doing things in bulk, and generally very difficult on larger images.

**Comment by aaronliu0130** [comment]
I'm pretty sure this is an issue with the models we can't fix, unless someone manages to find a model that works on tiles. You could also try to bulk crop everything.

**Comment by BrunoBieri** [comment]
@aaronliu0130 there would be a workaround without the need of special models that support that. This "Adrift" person made a video (https://youtu.be/uwWdf2pB7Ao) about how he solved it with two GIMP scripts which:

- basically takes the input image and stores it as 3x3 times source image
- do the upscale on that 3x3 image
- then crop out the central image again to "restore" the tiled image but upscaled

Would that be a way to implement it within upscayl? I know that using a 3x3 source image would slow down the up-scaling process (because of the image size) but I think it would be quite a feature to support tailed images as well. What do you think?

**Comment by oemsysadm** [comment]
It wouldn't even have to upscale the full 3x3, just a slight overscan window of the original one, then crop it back down.

That said, I think it's possible that various upscaling routines still wouldn't make pixel perfect upscaling of identical sections of the same image. It would depend on the algorithm. But it might get a lot closer.

**Comment by NayamAmarshe** [comment]
The only good solution is to train Real-ESRGAN on tiled images and create a new model.

**Comment by aaronliu0130** [comment]
@BrunoBieri That was what I was thinking of when I said bulk cropping. While this would be useful we have some other things to focus on right now, you can check out the 2.6 milestone.
