### ISSUE TITLE
Upscayl gives an error saying "unfortunately, we do not support cpu/igpu"

### ISSUE THREAD

**Issue by VeronMDevstudio** [upscayl/upscayl#298]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Upscayl fails to work on any image, giving the GPU not supported error. I have a GTX 1650(laptop) as my dGPU. 
- yes, I've tried reinstalling drivers
- yes, I set the GPU id to 0,1 or 2
- no, it is not an issue with the windows build, I've tried it on multiple build versions

### To Reproduce

Install and use upscayl on a machine running Win 11 with a GTX 1650

### Expected Behavior

Upscayl should enhance the image with no error

### Version/Commit Hash

2.0.1 Windows

### OS Specifics

GTX 1650, Windows 11 Pro Insider Preview 25352

### Screenshots

![image](https://user-images.githubusercontent.com/44627701/235654254-83a8ea62-08ed-4abc-8eef-b01e4bec04ba.png)
![image](https://user-images.githubusercontent.com/44627701/235654381-43ce02b5-df35-48c0-a5cf-34e57395e34c.png)

**Comment by aaronliu0130** [comment]
If you don’t have logs, you may follow these instructions: Download and install git from https://git-scm.com/download (note that git is bundled with macOS) and node from https://nodejs.org/en/download/current/ (choose standalone installer 64 for both) then run these in your terminal (if you don't know what this is, search and open an app on your computer called "Command Prompt" or "cmd" for short):
```sh
git clone https://github.com/TGS963/upscayl
cd upscayl
npm install
npm run start
```
After the last command, upscayl should show up. Reproduce the error and send out the terminal output. `npm` will tell you about audit errors. These are due to #54 and currently expected.

**Comment by Macka323** [comment]
I fixed it with disabling the gpu I don't need, in this case the integrated amd.
![image](https://github.com/upscayl/upscayl/assets/75259519/69b72fb0-c0f4-43ef-9ea9-3fcb06b0f907)
And it works
