### ISSUE TITLE
Cannot be used after the update

### ISSUE THREAD

**Issue by Dyin9Light** [upscayl/upscayl#315]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

<details>I tried to uninstall and reinstall the software but it didn't work
<summary>Logs</summary>
<pre>

⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\13017\Pictures\Saved Pictures\00035-3088948160-masterpiece, best quality, realistic，1boy，cyberpunk，science fiction，hair between eyes.png
🖼 Selected Image Path:  C:\Users\13017\Pictures\Saved Pictures\00035-3088948160-masterpiece, best quality, realistic，1boy，cyberpunk，science fiction，hair between eyes.png
📁 Selected Image Directory:  C:\Users\13017\Pictures\Saved Pictures
🖼 imagePath:  C:\Users\13017\Pictures\Saved Pictures\00035-3088948160-masterpiece, best quality, realistic，1boy，cyberpunk，science fiction，hair between eyes.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\13017\Pictures\Saved Pictures\00035-3088948160-masterpiece, best quality, realistic，1boy，cyberpunk，science fiction，hair between eyes.png,-o,C:\Users\13017\Pictures\Saved Pictures\00035-3088948160-masterpiece, best quality, realistic，1boy，cyberpunk，science fiction，hair between eyes_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\upscayl\resources\models,-n,realesrgan-x4plus,,-f,png
🐞 BACKEND REPORTED:  image upscayl:  [0 NVIDIA GeForce RTX 4060 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 4060 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\13017\Pictures\Saved Pictures\00035-3088948160-masterpiece, best quality, realistic，1boy，cyberpunk，science fiction，hair between eyes_upscayl_4x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\13017\Pictures\Saved Pictures\00035-3088948160-masterpiece, best quality, realistic，1boy，cyberpunk，science fiction，hair between eyes.png,-o,C:\Users\13017\Pictures\Saved Pictures\00035-3088948160-masterpiece, best quality, realistic，1boy，cyberpunk，science fiction，hair between eyes_upscayl_4x_realesrgan-x4plus.png,-s,4,-m,D:\upscayl\resources\models,-n,realesrgan-x4plus,,-f,png
🐞 BACKEND REPORTED:  image upscayl:  [0 NVIDIA GeForce RTX 4060 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 4060 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4060 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\13017\Pictures\Saved Pictures\00035-3088948160-masterpiece, best quality, realistic，1boy，cyberpunk，science fiction，hair between eyes_upscayl_4x_realesrgan-x4plus.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
</pre>
</details>

### To Reproduce

I started with version 2.0.1, it worked fine the first time I used it, then it didn't work, there was no loading process, and then I updated to version 2.5.1 and it still didn't work

### Expected Behavior

A loading process can occur and then an image can be output

### Version/Commit Hash

2.5.1

### OS Specifics

RTX4060   windows 11

### Screenshots

<img width="965" alt="微信图片_20230512192857" src="https://github.com/upscayl/upscayl/assets/133359871/7dfc7f76-aaa7-4da0-b28a-396c9c4194c8">

**Comment by TGS963** [comment]
I cannot see anything distinctly wrong with the logs. Could you try with other images or with this image in another location? And try to specify the output location somewhere else.

**Comment by teknoyhopi** [comment]
![image](https://github.com/upscayl/upscayl/assets/123451030/db634761-a1a6-4291-b262-63b61d6e8872)

me to :(

**Comment by TGS963** [comment]
I have tried using a file with the same name as the one on the log and it works fine. This must be something else

**Comment by PKK02** [comment]
Same here. Just downloaded it for the first time.

**Comment by ninotrivelli** [comment]
Im having the same issue, can't use it after the update.

![image](https://github.com/upscayl/upscayl/assets/72840054/60699e76-74fe-4eae-8eb5-40b5f78255ce)

It just messes up any image, no matter the model im using. :(

**Comment by TGS963** [comment]
Could you please provide your logs as well?

**Comment by aaronliu0130** [comment]
@ninotrivelli Did you change the "scale" slider?

**Comment by idrissiziad** [comment]
![2023-05-20 19_42_59-Window](https://github.com/upscayl/upscayl/assets/110735036/fad695a1-a3ab-4dd2-afea-6845553718a1)
It does not occur on Linux, precisely Fedora Workstation 38.
For Windows, version 2.0.1 worked correctly but after updating, it seems like it doesn't upscale since no file is exported after.
After downgrading to 2.0.1, the error is still there when it used to work correctly.

Logs:
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\Idrissi\Downloads\BMhk4EtpTcKDbK-qTD_IcVxK-ZE6Hak-4auIa3JIfRw.webp
🖼 Selected Image Path:  C:\Users\Idrissi\Downloads\BMhk4EtpTcKDbK-qTD_IcVxK-ZE6Hak-4auIa3JIfRw.webp
📁 Selected Image Directory:  C:\Users\Idrissi\Downloads
🖼 imagePath:  C:\Users\Idrissi\Downloads\BMhk4EtpTcKDbK-qTD_IcVxK-ZE6Hak-4auIa3JIfRw.webp
🔤 Extension:  webp
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Idrissi\Downloads\BMhk4EtpTcKDbK-qTD_IcVxK-ZE6Hak-4auIa3JIfRw.webp,-o,C:\Users\Idrissi\Downloads\BMhk4EtpTcKDbK-qTD_IcVxK-ZE6Hak-4auIa3JIfRw_upscayl_4x_realesrgan-x4plus-anime.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\Idrissi\Downloads\BMhk4EtpTcKDbK-qTD_IcVxK-ZE6Hak-4auIa3JIfRw_upscayl_4x_realesrgan-x4plus-anime.png
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage true

**Comment by TGS963** [comment]
Thanks for the logs. I'll try to reproduce this

**Comment by idrissiziad** [comment]
Thank you for your quick answer, feel free to contact me for additional information.

**Comment by TGS963** [comment]
I cannot replace this... @NayamAmarshe any idea what this might be?

**Comment by Nihilentropy-117** [comment]
Same issue here, Arch Linux, installed from AUR

**Comment by trevgleavitt** [comment]
Mine is doing the same thing. I'm on ubuntu 22.04. It's been doing this ever since the update. went back and downloaded an older version and it worked perfect but I can't keep the older version because it automatically downloads the newer version without me confirming. I've tried all sorts of different settings in addition to the default settings and no matter what, it creates a jumbled image.

**Comment by NayamAmarshe** [comment]
> I cannot replace this... @NayamAmarshe any idea what this might be?

Could be a driver issue. Ncnn would sometime generate empty images if it can't communicate with the driver.
