### ISSUE TITLE
Merge model names of different scales

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#348]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

After I import custom models, I see some cluttery model names that are just basically the same model with different scales:
![image](https://github.com/upscayl/upscayl/assets/11874211/08f78846-269a-4a02-a51f-cda8fb043f56)

### Description

Grey the slider by default. When models with name of preexisting model name + "-x2", "-x3", or "-x4" are detected, just merge their selection into their parent model and ungrey the corresponding slider option.

### Alternatives

Manually go and set BOTH the slider and the model each time while enduring clutter.
We could also merge these models into master or offer it as an in-app download pack after implementing the feature above.

**Comment by NayamAmarshe** [comment]
While this is a good idea, it won't always work since the models can be named anything. There's no way to detect the model if the name changes. So, at best, this would be a half-working implementation that might introduce more bugs than fix them.

As the custom models require extra research, I've made sure to mention that the models that animevideo we provide come in different scales. As of now, there are no other custom scale models available, other than x4.

**Comment by aaronliu0130** [comment]
I'm not sure what bugs this could introduce, and for me just filename detection should be enough.

**Comment by NayamAmarshe** [comment]
> I'm not sure what bugs this could introduce, and for me just filename detection should be enough.

Well, if you only need it for animevideo model, then I suppose it can be implemented but this would be a highly specific feature that won't be too modular.

**Comment by aaronliu0130** [comment]
Huh, I just realized that only animevideo is named like this. Maybe we should rename the other scale models?

**Comment by NayamAmarshe** [comment]
> Huh, I just realized that only animevideo is named like this. Maybe we should rename the other scale models?

Now that'd be too much from a user perspective. Suppose you convert a model, now you have to rename it and the rest of them to include x4 in their name only because of 1 random models. So adding step complexity on possibly 20+ models for 1 model of 3 types is not worth it.

I think it's better to set the scale according to the model. If the model has x4, we set it to x4. If the model has x2, we set it to x2. Otherwise, we let the users play with it.

**Comment by aaronliu0130** [comment]
Supporting our recognition and scaling system doesn’t need to be mandatory.
