### ISSUE TITLE
Save Image As JPG

### ISSUE THREAD

**Issue by Sam-Rev** [upscayl/upscayl#396]
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Hi Dear,
can you please add a features to let the upscaled images as JPG when uploaded as folder please ...?
Because we can't convert a hole folder from PNG to JPG again one by one, Thanks for your hard work

Have a good day

### Related Problem(s)

No

**Comment by aaronliu0130** [comment]
As said in the FAQ we can't do that because of a bug. There are image converters that can convert a folder to JPG, but there are too many and at least I'd rather let the user choose. See #174.
![compulsory rickrolls are issued for duplicates of other issues and the FAQ](https://github.com/upscayl/upscayl/assets/11874211/1b6870c9-bc20-419b-8f08-e4f77db239e5)

**Comment by Sam-Rev** [comment]
Thanks Nayam, we hope good news from you.

have a nice day
