### ISSUE TITLE
Custom commands

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#476]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Add a "custom command(s)" text field and toggle in settings that allow the user to specify a custom command to use for upscayling. When it is enabled, the main part of upscayl will not support selecting models or batch and upscayl will simply append the file name to the custom command.

Also add a "output filename" text field which will be used to display Upscayl's comparision, with the image on the right being the filename with `*` replaced with the input filename. Maybe also add a toggle that will switch the text field to specifying the name of the output path option, `-o` by default so Upscayl can simply hook into it. Similar field + toggles may also be added for batch and model selection.

Maybe also add built-in presets support.

This is obviously very ambitious and may require a refactor.

### Related Problem(s)

Many don't want to use Upscayl Cloud yet still want to use Upscayl's delicious interface. With this implemented, we can add configuration presets in the wiki to support things like face restoration.

### Alternatives

direct them to upscayl cloud

**Comment by NayamAmarshe** [comment]
Like I said before, this is simply not possible.
Face restoration is not something that's integrated in Real-ESRGAN NCNN Vulkan.

I see no reason for custom commands because Upscayl already exposes all the different options available by the Real-ESRGAN binary. There's nothing more to add or remove to be honest.

Cloud Upscayl is different because it's a single server, with a fixed configuration and everything so we can do a lot more than just upscaling images. That also includes removing backgrounds.

Upscayl Desktop cannot have the same features because there are multiple platforms, multiple edge cases to handle and we have to provide a solution that works OOTB.

**Comment by aaronliu0130** [comment]
Custom commands would be able to use ANY CLI, not just Real-ESRGAN. We don't have to bake in all the different flags for everything to add this feature; the user will specify them.

**Comment by NayamAmarshe** [comment]
I still don't think that's viable.

You're essentially talking about a universal GUI for CLI, which isn't possible.

1. Not every CLI command is the same, and not every AI model has a CLI.
2. Setting up CLI is a lot of work sometimes. Even installing Real-ESRGAN is quite painful.
3. Most of these AI projects do not allow you to process a single image, rather a whole directly.
4. This is simply beyond the scope of Upscayl Desktop. The project's goal is to provide simple image upscaling for all platforms without any fuss OOTB, and not be a one size fits all solution for image processing.

This is something that is way too advanced for most of our user base and requires development effort, which would eventually lead to feature creep.

I personally am not in favor of something like this, although I'd say that if the Upscayl tem grows in size and gets bigger down the line, it's something we could consider.
