### ISSUE TITLE
improve software UI and add Codeformer model

### ISSUE THREAD

**Issue by SpiritPowerTX** [upscayl/upscayl#494]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

- Ability to activate simple face restauration models (for exemple CodeFormer)
- Ability to better control settings

STEP 1 ➡️ Select your pictures :
[] manualy select pictures  >> button [ BROWSE ... ] (multiple files or just one file)
[] auto-detect pictures inside folders  >> button [ BROWSE ... ] (multiple folders or just one folder)

[✅] Activate super upscaling !
choise your model :
ESRPGAN, ANIME 4x, etc....

choise your power :
[ x2 ]
(( x4 )) << (default)
[ x8 ]
[ x16 ]

[✅] Activate face enhancement ! it will work after the upsacaler process (if selected)
Choice your model :
>> CodeFormer <<
== DeepFace

Face fidelity : 33 %
[=====O--------------------]

FINAL STEP  ➡️  button : [ >> Go magic ! << ]

**Comment by aaronliu0130** [comment]
Thanks for your interest!

**Comment by SpiritPowerTX** [comment]
hello, ok 😭🤣

"2 - Putting face enhancement as post processing is very wrong." : Why ?

4 : it is the upscaling factor ! (better increase the size of the image with the models)
choise your Upscayl size :
[ x2 ]
[ x4 ] << (default factor)
[ x8 ]
[ x16 ]
Currently we can only choise x4 or x2 (hum.. x4 only for version 2.8.6  i see)

5 : Sorry i don't understand what do you mean

**Comment by aaronliu0130** [comment]
2: Face enhancement is basically upscaling but specifically trained for faces. Post processing is doing various adjustments you can with iOS Photos <em>after</em> upscaling.
5: I understand what you mean as I know how it was before but I think the user would be very confused to open their app and see "choose your power" "go magic!" especially when all our branding is just "Upscayl" instead of "Magic Upscale" or something like that
