### ISSUE TITLE
Doesn't work on imac 27 macOS 10.14 Core i5 + Radeon Pro 580

### ISSUE THREAD

**Issue by Xajel** [upscayl/upscayl#59]
I'm running the latest version (v1.2.0) on an iMac 5K with Core i5 and Radeon Pro 580 8GB, running macOS Mojave 10.14.6.

Whenever I process any image, the processing stops at 97.53% and shows this message:

"This image is possibly corrupt or not supported by Upscayl. You could try converting the image into another format and upscaling again. Otherwise, make sure that the output path is correct and you have the proper write permissions for the directory. If not, then unfortuantely this image is not supported by Upscayl, sorry."

This happens with any image; even when I create a simple image in Photoshop. Processing the same images in another system totally works, even on my intel 12th gen laptop (with no dGPU) as the iGPU on 12th gen supports Vulkan.

**Comment by NayamAmarshe** [comment]
Okay, I'll try it on my machine. I have a 580 as well.

**Comment by NayamAmarshe** [comment]
btw, that error appears when there's an encoding/decoding error. If all your images are getting that error, it's possible that the GPU is not supporting those particular vulkan calls or something.

**Comment by Xajel** [comment]
I have a non-5k iMac system also with a much older GPU (GeForce GTX 775) and it works fine, albeit slow.

The process always end at the end, sometimes 96% and sometimes 97.x. But it almost always after 95%.

**Comment by johnblommers** [comment]
Try it on the image [to_upscale.jpeg](https://github.com/upscayl/upscayl/blob/main/to_upscale.jpeg)   located in this repository

**Comment by Xajel** [comment]
> 

Tried the to_upscale.jpeg. It stopped at 50% with the same error.

**Comment by NayamAmarshe** [comment]
> > 
> 
> Tried the to_upscale.jpeg. It stopped at 50% with the same error.

Hey, sorry for the late response but I think it could be a hardware specific issue. Real-ESRGAN also has a few bugs. Can you try running Upscayl through commandline?

**Comment by johnblommers** [comment]
Part of the problem here is that it's unclear how to tell which Macintosh Upscayl will run on. Apple provides Metal not Vulkan so Upscayl must have some kind of translation software that goes Vulkan to Metal.

Perhaps the dev team is able to provide guidance as to which Macintosh models are able to run Upscayl. Else we see this kind of thing

![Screen Shot 2022-09-11 at 8 02 08 PM](https://user-images.githubusercontent.com/8484427/189782559-45e13e03-f405-4ff1-a8fe-0ee8ec6143e5.png)

**Comment by NayamAmarshe** [comment]
6970M doesn't support Vulkan and sorry, I can't really tell you all the models where Upscayl doesn't work since it's Linux-first and I don't know much about the Apple world of things. Most users are able to use this on most modern Mac machines.

As for Radeon Pro 580, I believe machine-specific issues are really out of my domain. Sorry that I can't help with them.
