### ISSUE TITLE
Release 2.9.9?

### ISSUE THREAD

**Issue by aaronliu0130** [upscayl/upscayl#673]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

We've made at least two quite important fixes: #653, and [(hopefully) bumping the minimum required version reflected by the app to macOS 12](fb609ea) so that we can finally have [bcome hombrew casc](https://github.com/Homebrew/homebrew-cask/pull/165335#event-11604367945). Somebody's made a gentoo package, so maybe we should release a 2.9.9 soon?

### Related Problem(s)

#653

**Comment by NayamAmarshe** [comment]
Yessir! I'll try for this weekend!

**Comment by Zeeshan-bk** [comment]
Hi @NayamAmarshe, thank you for your hard work on this amazing software. I am eagerly waiting for the next update, as I have been unable to use my favorite upscaling tool for two weeks due to the bug hindering the conversion of upscaled PNG to JPG. Could you please release it as soon as possible? I appreciate your efforts and dedication. 😊
