### ISSUE TITLE
JpegXL output format option

### ISSUE THREAD

**Issue by upscaylandcompress** [upscayl/upscayl#678]
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Both png and webp formats are nice, but there is jpegxl with beats both in terms of compression ratio and that's with the mathematically lossless option. If the quality would be lowered like is with the jpeg output format, it would crush them even more. JpegXL compression is at least half the size of png and compared to webp, it doesn't have 16k by 16k maximum pixel size which might be a problem here since we are talking about upscaling images.

cjxl should be used with --distance=0 for perfect reproduction of the original upscaled file, may that be ppm, png, webp and with --effort=9 for maximum compression

**Comment by NayamAmarshe** [comment]
No plans for that yet.
JXL is supported by sharp.js but not upscayl-ncnn.

Most devices or browsers also do not support it out of the box, so, I'll mark this as 'not planned' for now.

**Comment by RafaelLinux** [comment]
Usually, many of us use rescaling because we are going to print the image. The available export formats lose colour depth. TIFF could be used instead of JXL, but nowadays, the best for printing option is JXL because it is a format that, in its conception, supports all the necessary (compression and keeping the colour depth) to go from RAW to JXL and rescale it afterwards with Upscayl.

That is the reason why we would like to incorporate JXL for exporting.

Thanks

**Comment by NayamAmarshe** [comment]
We can consider it for Upscayl Cloud because it's got a better and coherent stack. On desktop, things get messier.

**Comment by RafaelLinux** [comment]
What's Upscayl Cloud?
