### ISSUE TITLE
Upscayl Slow Down My Windows 7 Computer Quite A Bit 

### ISSUE THREAD

**Issue by DJboutit** [upscayl/upscayl#94]
My computer specs I7 3770 24gb DDR3 RX 6600 with Windows 7

When processing images with Windows 7 the program slow down my computer 50% to 65%.  I have a 2nd HD in my computer running Windows 10 I do not use it much this program does not seem to slow down my computer if it does it is only like 10% to 15%.
This issue with slowing down a computer running Windows 7 need to be fixed

**Comment by NayamAmarshe** [comment]
Upscayl doesn't support Windows 7, at least as far as maintenance goes because not even Microsoft would support your OS.

I'm marking this issue as WONTFIX because I honestly cannot provide proper support for Windows, let alone Windows 7. There's nothing extra that I can do to fix the issue for you unfortunately.

Your options are: Either use a better Windows exclusive upscaler app or use Upscayl on a linux based OS like ZorinOS (which is what I use).

**Comment by DJboutit** [comment]
A lot of people still use Windows 7 some peoples computer can bearly run Windows 10 so they stick with Windows 7.

**Comment by NayamAmarshe** [comment]
I wouldn't recommend that tbh. Windows 7 security is like a Cheeto in place of a steel lock, it's way too easy to get a ransomware and malware on Windows 7 these days and the software compatibility rate is going down faster than ever, it's just better to move to Linux instead of trying to keep an obsolete OS alive. Not only does Linux have better software compatibility but also runs just as fast if not faster than Windows 7 and you don't get any bloatware/spyware like Windows 10/11 either.

**Comment by Woisek** [comment]
> A lot of people still use Windows 7 some peoples computer can bearly run Windows 10 so they stick with Windows 7.

Well, buy a better computer then, what reason should that be, sorry? 🤷‍♂️
